### ISSUE TITLE
Copying code from CodeApprove adds extraneous line breaks

### ISSUE THREAD

**Issue by mtlynch** [codeapprove/feedback#56]
If I copy the following code from a CodeApprove diff:

```yaml
  pip:
    # Ensure cryptography is installed into the global Python environment, even
    # when Ansible is running from within a Python virtual environment.
```

When I paste the text, it has extra newlines:

```yaml
  pip:

    # Ensure cryptography is installed into the global Python environment, even

    # when Ansible is running from within a Python virtual environment.
```

**Comment by samatcodeapprove** [comment]
This bug is fixed in today's release.

**Comment by mtlynch** [comment]
@samatcodeapprove - I'm still seeing the extra newlines.

I'm on a Windows 10 system if that matters. But for example, on this PR: https://codeapprove.com/pr/tiny-pilot/tinypilot/1296?head=86fae61abb9502fe87d487c6f9da5abd7416c272

Any lines I copy, when I paste them to Notepad or VS Code, I see extra newlines on every line.

**Comment by samatcodeapprove** [comment]
Ah the Windows part may actually matter (since we’re dealing with
newlines)! I’ve got a Windows machine I can test on.
